nr_neighbor_cells = (

  # DU-1 (PCI 0)
  {
    servingCellPhysCellId = 0;
    neighbors = (
      {
        physCellId = 1;
        nrCellId = 12345679L;
        trackingAreaCode = 2;
        absoluteFrequencySSB = 641280;
        subcarrierSpacing = 1;
        frequencyBand = 78;
        blacklisted = "false";
      }
    );
  },

  # DU-2 (PCI 1)
  {
    servingCellPhysCellId = 1;
    neighbors = (
      {
        physCellId = 0;
        nrCellId = 12345678L;
        trackingAreaCode = 1;
        absoluteFrequencySSB = 641280;
        subcarrierSpacing = 1;
        frequencyBand = 78;
        blacklisted = "false";
      },
      {
        physCellId = 2;
        nrCellId = 12345680L;
        trackingAreaCode = 3;
        absoluteFrequencySSB = 641280;
        subcarrierSpacing = 1;
        frequencyBand = 78;
        blacklisted = "false";
      }
    );
  },

  # DU-3 (PCI 2)
  {
    servingCellPhysCellId = 2;
    neighbors = (
      {
        physCellId = 1;
        nrCellId = 12345679L;
        trackingAreaCode = 2;
        absoluteFrequencySSB = 641280;
        subcarrierSpacing = 1;
        frequencyBand = 78;
        blacklisted = "false";
      },
      {
        physCellId = 3;
        nrCellId = 12345689L;
        trackingAreaCode = 4;
        absoluteFrequencySSB = 641280;
        subcarrierSpacing = 1;
        frequencyBand = 78;
        blacklisted = "false";
      }
    );
  },

  # DU-4 (PCI 3)
  {
    servingCellPhysCellId = 3;
    neighbors = (
      {
        physCellId = 2;
        nrCellId = 12345680L;
        trackingAreaCode = 3;
        absoluteFrequencySSB = 641280;
        subcarrierSpacing = 1;
        frequencyBand = 78;
        blacklisted = "false";
      }
    );
  }

);

